"""
One-time calibration tool.

Click points on a background-removed garment image, in this exact order.
Tops (default) - defined once in garment_overlay.POINT_NAMES, so this file
and the runtime overlay can never disagree about ordering:
  1. Left shoulder
  2. Right shoulder
  3. Hip center   (roughly where the hips would sit, centered horizontally)
  4. Left elbow   \
  5. Right elbow   } optional - skip for a sleeveless top/dress
  6. Left wrist    } (press s once the first 3 are placed)
  7. Right wrist  /

Bottoms (--bottom) - garment_overlay_bottom.POINT_NAMES_BOTTOM:
  1. Hip center   (roughly where the waistband centers horizontally)
  2. Left waist   (top-left corner of the waistband)
  3. Right waist  (top-right corner of the waistband)
  4. Crotch       (where the legs separate - or just a bottom-center
                   reference point, e.g. for a skirt with no leg seam)
  5. Left knee    \
  6. Right knee     } optional - skip for a skirt
  7. Left ankle     } (press s once the first 4 are placed)
  8. Right ankle  /

The points past each list's core prefix are exactly the ones a sleeveless
top or a skirt doesn't need — pressing s early only saves the points you
actually clicked. What actually enforces "every point a garment's declared
segments need must exist" is garment_rig.check_calibration at runtime, not
this file — so calibrate.py itself never needs to know which segments a
garment ends up declaring.

These become the correspondences the runtime rigid warp is fit against each
frame — whichever of these points has a currently-visible match on the
body (shoulders/hips are always required; the rest are used
opportunistically) get fed into the fit.

Saves a sidecar JSON next to the image: <name>.anchors.json

Usage:
    python calibrate.py garments/white_top.png

    for bottoms (pants, shorts, skirts):
    python calibrate.py garments/green_pants.png --bottom

    add segments and occluders by hand to the JSON if they're not there,
    garment_library.py will not run if the JSON is missing those keys.
    the keys are automatically generated by fashn program

Controls:
    click   - place the next point
    u       - undo last point
    s       - save (once the core points for this garment kind are placed)
    q       - quit without saving
"""
import sys
import json
from pathlib import Path

import cv2

from anchor_session import POINT_COLORS, composite_on_checkerboard
from garment_overlay import POINT_NAMES, CORE_POINT_COUNT as CORE_POINT_COUNT_TOP
from garment_overlay_bottom import POINT_NAMES_BOTTOM, CORE_POINT_COUNT as CORE_POINT_COUNT_BOTTOM

# normalize.py caps the long edge
MAX_WINDOW_HEIGHT = 950


def calibrate(image_path: str, point_names: list, core_count: int) -> dict:
    rgba = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)
    if rgba is None:
        raise FileNotFoundError(f"Could not read image: {image_path}")

    scale = min(1.0, MAX_WINDOW_HEIGHT / rgba.shape[0])
    if scale < 1.0:
        rgba = cv2.resize(rgba, None, fx=scale, fy=scale, interpolation=cv2.INTER_AREA)

    display_base = composite_on_checkerboard(rgba)
    points = []

    def on_mouse(event, x, y, flags, userdata):
        if event == cv2.EVENT_LBUTTONDOWN and len(points) < len(point_names):
            points.append((x, y))

    window_name = "Calibration - click each point in order (u=undo, s=save, q=quit)"
    cv2.namedWindow(window_name)
    cv2.setMouseCallback(window_name, on_mouse)

    while True:
        frame = display_base.copy()
        for i, (px, py) in enumerate(points):
            color = POINT_COLORS[i % len(POINT_COLORS)]
            cv2.circle(frame, (px, py), 6, color, -1)
            cv2.putText(frame, point_names[i], (px + 8, py - 8),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

        can_save = len(points) >= core_count
        if len(points) < len(point_names):
            next_label = f"{point_names[len(points)]}" + ("" if len(points) < core_count else " (optional)")
        else:
            next_label = "all points set"
        status = f"click: {next_label}" + ("  |  s = save now" if can_save else "")
        cv2.putText(frame, status, (10, 25),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)

        cv2.imshow(window_name, frame)
        key = cv2.waitKey(20) & 0xFF

        if key == ord('u') and points:
            points.pop()
        elif key == ord('s'):
            if can_save:
                break
            print(f"Need at least the first {core_count} (core) points before saving "
                  f"({len(points)} placed so far).")
        elif key == ord('q'):
            cv2.destroyAllWindows()
            sys.exit("Calibration cancelled.")

    cv2.destroyAllWindows()

    return {name: [round(x / scale), round(y / scale)]
            for name, (x, y) in zip(point_names, points)}


def save_anchors(image_path: str, anchors: dict) -> str:
    """
    Write the clicked points to <image>.anchors.json, preserving any keys
    already in that file (namely "segments"/"occluders" - calibrate.py
    never writes those itself, so re-calibrating an already-configured
    garment must not erase them).
    """
    out_path = str(Path(image_path).with_suffix("")) + ".anchors.json"
    existing = {}
    if Path(out_path).exists():
        with open(out_path) as f:
            existing = json.load(f)
    with open(out_path, "w") as f:
        json.dump({**existing, **anchors}, f, indent=2)
    return out_path


if __name__ == "__main__":
    args = sys.argv[1:]
    is_bottom = "--bottom" in args
    if is_bottom:
        args.remove("--bottom")
    if len(args) != 1:
        sys.exit("Usage: python calibrate.py path/to/garment.out.png [--bottom]")

    img_path = args[0]
    point_names = POINT_NAMES_BOTTOM if is_bottom else POINT_NAMES
    core_count = CORE_POINT_COUNT_BOTTOM if is_bottom else CORE_POINT_COUNT_TOP
    anchors = calibrate(img_path, point_names, core_count)
    out_path = save_anchors(img_path, anchors)
    print(f"Saved anchors to: {out_path}")
    print(anchors)
